name: Test
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "src/**"
      - "tests/**"

jobs:
  build:
    name: Test code
    strategy:
      matrix:
        version: [19.x, 18.x, 16.x, 14.x]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        # setup nodejs
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.version }} # Version range or exact version of a Node.js version to use, using SemVer's version range syntax
      # setup pnpm
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "7.13.x"
          run_install: true
      # this gives an exit code
      - name: Test
        run: pnpm run test
